import { NextResponse } from 'next/server'
import jwt from 'jsonwebtoken'
import bcrypt from 'bcryptjs'
import { prisma } from '@/lib/prisma'
import { withCORS } from '@/lib/cors'

const JWT_SECRET = process.env.JWT_SECRET || 'your-secret-key'

const handler = async (req: Request) => {
  try {
    const body = await req.json()
    console.log('Registration request body:', body)

    const { email, name, password, phoneNumber, referralCode, username, role: requestedRole } = body

    // Validate required fields
    if (!email || !name || !password || !phoneNumber) {
      console.log('Missing required fields:', { email, name, password: !!password, phoneNumber })
      return NextResponse.json(
        { message: 'All fields are required' },
        { status: 400 }
      )
    }

    // Auto-generate username if not provided
    let normalizedUsername: string;
    let isAutoGenerated = false;
    if (username) {
      // Normalize and validate provided username
      const rawUsername: string = String(username).trim()
      normalizedUsername = rawUsername.toLowerCase()
      const usernameRegex = /^[a-z0-9_\.]{3,20}$/
      if (!usernameRegex.test(normalizedUsername)) {
        return NextResponse.json(
          { message: 'Invalid username. Use 3-20 chars: a-z, 0-9, underscore or dot' },
          { status: 400 }
        )
      }
    } else {
      // Auto-generate username from email (before @) or name
      isAutoGenerated = true;
      const baseUsername = email.split('@')[0].toLowerCase().replace(/[^a-z0-9]/g, '')
      normalizedUsername = baseUsername || name.toLowerCase().replace(/[^a-z0-9]/g, '').substring(0, 20)
      
      // Ensure username is at least 3 characters
      if (normalizedUsername.length < 3) {
        normalizedUsername = normalizedUsername + Math.random().toString(36).substring(2, 5)
      }
      
      // Ensure username is max 20 characters
      normalizedUsername = normalizedUsername.substring(0, 20)
      
      // Add random suffix if username already exists
      let finalUsername = normalizedUsername
      let attempts = 0
      while (attempts < 10) {
        const exists = await prisma.user.findUnique({
          where: { username: finalUsername },
          select: { id: true }
        })
        if (!exists) break
        finalUsername = normalizedUsername + Math.random().toString(36).substring(2, 5)
        attempts++
      }
      normalizedUsername = finalUsername
    }

    // Normalise and validate role (default to STUDENT)
    const allowedRoles = ['STUDENT', 'ADMIN'] as const
    type AllowedRole = (typeof allowedRoles)[number]
    let selectedRole: AllowedRole = 'STUDENT'

    if (typeof requestedRole === 'string') {
      const candidate = requestedRole.toUpperCase()
      if (allowedRoles.includes(candidate as AllowedRole)) {
        selectedRole = candidate as AllowedRole
      } else {
        console.warn('[REGISTER] Invalid role requested, defaulting to STUDENT:', { requestedRole })
      }
    }

    // Check if user already exists (email)
    const existingUser = await prisma.user.findUnique({ where: { email } })

    if (existingUser) {
      console.log('User already exists:', email)
      return NextResponse.json(
        { message: 'User already exists' },
        { status: 400 }
      )
    }

    // Check username uniqueness (only if username was manually provided, auto-generated ones are already checked)
    if (!isAutoGenerated) {
      const existingUsername = await prisma.user.findUnique({
        where: { username: normalizedUsername },
        select: { id: true }
      })
      if (existingUsername) {
        return NextResponse.json(
          { message: 'Username not available' },
          { status: 400 }
        )
      }
    }

    // Validate referral code if provided
    let referrerId = null;
    if (referralCode) {
      const referrer = await prisma.user.findUnique({
        where: { referralCode },
        select: { id: true }
      });
      
      if (!referrer) {
        return NextResponse.json(
          { message: 'Invalid referral code' },
          { status: 400 }
        );
      }
      
      // Prevent self-referral
      if (referrer.id === email) {
        return NextResponse.json(
          { message: 'Cannot use your own referral code' },
          { status: 400 }
        );
      }
      
      referrerId = referrer.id;
      console.log('Referral code validated:', { referralCode, referrerId });
    }

    // Validate password strength
    if (password.length < 6) {
      return NextResponse.json(
        { message: 'Password must be at least 6 characters long' },
        { status: 400 }
      )
    }

    // Hash password (bcrypt.hash automatically generates salt)
    const hashedPassword = await bcrypt.hash(password, 10)
    
    // Validate hash was created correctly (bcrypt hashes are always 60 characters)
    if (!hashedPassword || hashedPassword.length !== 60) {
      console.error('[REGISTER] Invalid password hash generated:', {
        hashLength: hashedPassword?.length,
        hashPrefix: hashedPassword?.substring(0, 20)
      })
      return NextResponse.json(
        { message: 'Password hashing failed. Please try again.' },
        { status: 500 }
      )
    }
    
    // Debug logging
    console.log('[REGISTER] Password hashing successful:', {
      passwordLength: password.length,
      hashedPasswordLength: hashedPassword.length,
      hashedPasswordPrefix: hashedPassword.substring(0, 20) + '...',
      isValidHash: hashedPassword.length === 60
    })

    // Create new user with referral info
    const user = await prisma.user.create({
      data: {
        email,
        name,
        hashedPassword,
        phoneNumber,
        username: normalizedUsername,
        role: selectedRole,
        referredBy: referralCode || null,
      },
    })

    // Verify password was stored correctly
    const verifyUser = await prisma.user.findUnique({
      where: { id: user.id },
      select: { id: true, email: true, hashedPassword: true }
    })
    
    // Verify stored password hash is valid
    if (!verifyUser?.hashedPassword || verifyUser.hashedPassword.length !== 60) {
      console.error('[REGISTER] Password hash validation failed after storage:', {
        userId: user.id,
        storedHashLength: verifyUser?.hashedPassword?.length,
        expectedLength: 60
      })
      // Delete the user if password wasn't stored correctly
      await prisma.user.delete({ where: { id: user.id } })
      return NextResponse.json(
        { message: 'Password storage failed. Please try again.' },
        { status: 500 }
      )
    }
    
    // Test password verification to ensure it works
    const testVerification = await bcrypt.compare(password, verifyUser.hashedPassword)
    if (!testVerification) {
      console.error('[REGISTER] Password verification test failed after storage')
      await prisma.user.delete({ where: { id: user.id } })
      return NextResponse.json(
        { message: 'Password verification failed. Please try again.' },
        { status: 500 }
      )
    }
    
    console.log('[REGISTER] User created and verified successfully:', { 
      id: user.id, 
      email: user.email,
      username: user.username,
      hashedPasswordStored: !!verifyUser?.hashedPassword,
      hashedPasswordLength: verifyUser?.hashedPassword?.length,
      passwordVerified: testVerification
    })

    // If referral code was used, process the referral
    if (referralCode && referrerId) {
      try {
        // Use transaction to ensure data consistency
        await prisma.$transaction(async (tx: any) => {
          // Create referral record
          await tx.referral.create({
            data: {
              referrerId,
              referredId: user.id,
              code: referralCode
            }
          });

          // Update referrer's stats
          await tx.user.update({
            where: { id: referrerId },
            data: {
              referralCount: { increment: 1 },
              totalReferralEarnings: { increment: 50 },
              wallet: { increment: 50 }
            }
          });

          // Update new user's wallet
          await tx.user.update({
            where: { id: user.id },
            data: {
              wallet: { increment: 50 }
            }
          });

          // Create transaction record for referrer
          await tx.transaction.create({
            data: {
              userId: referrerId,
              amount: 50,
              type: 'REFERRAL_BONUS',
              status: 'COMPLETED'
            }
          });

          // Create transaction record for new user
          await tx.transaction.create({
            data: {
              userId: user.id,
              amount: 50,
              type: 'REFERRAL_BONUS',
              status: 'COMPLETED'
            }
          });
        });

        console.log('Referral processed successfully:', { referralCode, referrerId, userId: user.id });
      } catch (referralError) {
        console.error('Error processing referral:', referralError);
        // Don't fail registration if referral processing fails
      }
    }

    // Generate JWT token
    const token = jwt.sign(
      { userId: user.id, role: user.role },
      JWT_SECRET,
      { expiresIn: '7d' }
    )

    return NextResponse.json({
      token,
      role: user.role,
      message: 'Registration successful',
    })
  } catch (error) {
    console.error('Registration error details:', error)
    
    // Check for Prisma errors
    if ((error as any).code === 'P2002') {
      const target = (error as any).meta?.target as string[] | undefined
      const field = Array.isArray(target) ? target.join(',') : String(target || '')
      const message = field.includes('username') ? 'Username not available' : 'Email already exists'
      return NextResponse.json({ message }, { status: 400 })
    }

    return NextResponse.json(
      { message: 'Internal server error', error: (error as any).message },
      { status: 500 }
    )
  }
}

export const POST = withCORS(handler)
export const OPTIONS = withCORS(() => new Response(null, { status: 204 })) 